#!/usr/bin/env bash
# 02-bootstrap.sh — fetch dispatcher source, lay down secrets, bring up
# the docker compose stack.
#
# Idempotent. Re-runs:
#   - `git fetch && git checkout origin/main` instead of re-cloning
#   - DOES NOT overwrite an existing `.env` — secrets are written once,
#     captured by the operator, and never regenerated. To rotate, the
#     operator edits .env in place.
#   - `docker compose up -d --build` will rebuild only if the image is
#     outdated (compose handles this).
#
# Sensitive: the FIRST run prints the bootstrap admin password to stdout
# once. Capture it.

set -euo pipefail

step() { echo; echo "▶ $*"; }

REPO_URL="${REPO_URL:-https://github.com/jefflower/dialect-labeler.git}"
REPO_BRANCH="${REPO_BRANCH:-main}"
REPO_DIR="${REPO_DIR:-/srv/dispatcher-repo}"
APP_DIR="${APP_DIR:-/srv/dispatcher}"
# Default: RFC 2606 reserved example.com — pydantic's EmailStr (via
# email-validator) REJECTS .local / .test / .invalid / .localhost as
# RFC 6762 reserved names, so naive defaults like admin@dispatcher.local
# cause 422 on login. Override at deploy time if you have a real
# admin mailbox you want to use:
#   ADMIN_EMAIL=ops@yourcompany.com bash 02-bootstrap.sh
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"

# ---------------------------------------------------------------------------
step "1. fetch source"
# ---------------------------------------------------------------------------
# Three valid layouts at this point:
#   (a) Standard clone path — REPO_DIR is a git checkout, APP_DIR is a
#       symlink into it. This is the long-term form (what later
#       `git pull` upgrades work against).
#   (b) Pre-existing real directory at APP_DIR with a docker-compose.yml
#       — e.g. an initial `rsync` from a developer's machine when
#       GitHub access from the box is flaky. We keep it as-is and just
#       move on, the operator can convert to (a) later by `rm -rf
#       /srv/dispatcher && rerun this script`.
#   (c) Nothing on disk yet — clone from REPO_URL.
if [[ -f "$APP_DIR/docker-compose.yml" && ! -L "$APP_DIR" ]]; then
  echo "$APP_DIR is a populated directory (no .git); leaving it alone."
  echo "to switch to git-managed upgrades later: rm -rf $APP_DIR && re-run."
elif [[ -d "$REPO_DIR/.git" ]]; then
  echo "updating $REPO_DIR…"
  git -C "$REPO_DIR" fetch origin
  git -C "$REPO_DIR" checkout "$REPO_BRANCH"
  git -C "$REPO_DIR" reset --hard "origin/$REPO_BRANCH"
  if [[ ! -L "$APP_DIR" ]] || \
     [[ "$(readlink "$APP_DIR")" != "$REPO_DIR/services/dispatcher" ]]; then
    rm -f "$APP_DIR"
    ln -s "$REPO_DIR/services/dispatcher" "$APP_DIR"
  fi
else
  mkdir -p "$(dirname "$REPO_DIR")"
  echo "cloning $REPO_URL (sparse, services/dispatcher only)…"
  git clone --depth 1 --filter=blob:none --sparse \
    "$REPO_URL" "$REPO_DIR"
  git -C "$REPO_DIR" sparse-checkout set services/dispatcher
  rm -f "$APP_DIR"
  ln -s "$REPO_DIR/services/dispatcher" "$APP_DIR"
fi
ls -la "$APP_DIR" | head -3
cd "$APP_DIR"

# ---------------------------------------------------------------------------
step "2. .env"
# ---------------------------------------------------------------------------
if [[ -f .env ]]; then
  echo ".env already exists — leaving it alone."
  echo "to rotate JWT_SECRET or admin password, edit .env in place + restart."
else
  JWT_SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"
  ADMIN_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')"
  cat > .env <<EOF
# Generated by scripts/deploy/02-bootstrap.sh on $(date -u +%FT%TZ)
JWT_SECRET=$JWT_SECRET
JWT_TTL_HOURS=720
JWT_REFRESH_AFTER_HOURS=24

# First-boot bootstrap admin. main.py only seeds if the users table is
# empty, so leaving these set after the first launch is mostly harmless
# — but it's good hygiene to clear them after capturing the password.
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD

# Closed-beta mode: admin must invite each user via the admin UI.
ALLOW_OPEN_REGISTRATION=false

# Storage + retention.
STORAGE_DIR=/data/storage
OUTPUT_TTL_HOURS=168
FAILED_INPUT_TTL_HOURS=72
LEASE_TTL_SECONDS=300
MAX_ATTEMPTS=3
CLEAN_INTERVAL_SECONDS=300
MAX_UPLOAD_BYTES=5368709120
EOF
  chmod 600 .env
  echo
  echo "================================================================"
  echo "‼ CAPTURE THIS NOW — bootstrap admin credentials"
  echo "  email:    $ADMIN_EMAIL"
  echo "  password: $ADMIN_PASSWORD"
  echo "================================================================"
  echo
fi

# ---------------------------------------------------------------------------
step "3. data dir"
# ---------------------------------------------------------------------------
# The docker compose file bind-mounts ./data → /data inside the container.
# We pre-create ./data here so the SQLite and uploaded-files paths exist
# before uvicorn starts.
mkdir -p data/storage

# ---------------------------------------------------------------------------
step "4. docker compose up"
# ---------------------------------------------------------------------------
docker compose up -d --build

# ---------------------------------------------------------------------------
step "5. wait for healthz"
# ---------------------------------------------------------------------------
ok=0
for i in {1..30}; do
  if curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
    ok=1
    break
  fi
  sleep 1
done
if [[ $ok -eq 1 ]]; then
  echo "✅ dispatcher healthy on http://127.0.0.1:8080"
else
  echo "❌ dispatcher did NOT come up within 30s. docker compose logs:"
  docker compose logs --tail 50
  exit 1
fi

echo
echo "✅ 02-bootstrap.sh complete"
echo "Next: scripts/deploy/03-caddy.sh"
